<a href="https://colab.research.google.com/github/brahmandamsasanka/Practice/blob/Practice-6%2F11%2F25/Practice_6_11_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [6]:
# Sample Data as a dictionary
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "Date": ["2025-06-01", "2025-06-02", "2025-06-02", "2025-06-03",
             "2025-06-04", "2025-06-04", "2025-06-05", "2025-06-05"],
    "Customer": ["Asha Rao", "Ravi Kumar", "Neha Patel", "Sunil Verma",
                 "Asha Rao", "Ravi Kumar", "Neha Patel", "Sunil Verma"],
    "Product": ["Notebook", "Ball Pen", "Laptop", "Mouse",
                "Pencil Box", "USB Drive", "Water Bottle", "Notebook"],
    "Category": ["Stationery", "Stationery", "Electronics", "Electronics",
                 "Stationery", "Electronics", "Lifestyle", "Stationery"],
    "Quantity": [3, 5, 1, 2, 1, 4, 2, 5],
    "Price": [50, 10, 55000, 500, 120, 800, 250, 50],
    "City": ["Mumbai", "Bengaluru", "Delhi", "Mumbai",
             "Chennai", "Bengaluru", "Hyderabad", "Chennai"]
}

df = pd.DataFrame(data)

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'])

print(df.head())

   OrderID       Date     Customer     Product     Category  Quantity  Price  \
0     1001 2025-06-01     Asha Rao    Notebook   Stationery         3     50
1     1002 2025-06-02   Ravi Kumar    Ball Pen   Stationery         5     10
2     1003 2025-06-02   Neha Patel      Laptop  Electronics         1  55000
3     1004 2025-06-03  Sunil Verma       Mouse  Electronics         2    500
4     1005 2025-06-04     Asha Rao  Pencil Box   Stationery         1    120

        City
0     Mumbai
1  Bengaluru
2      Delhi
3     Mumbai
4    Chennai

In [7]:
df.head()

,OrderID,Date,Customer,Product,Category,Quantity,Price,City
0,1001,2025-06-01,Asha Rao,Notebook,Stationery,3,50,Mumbai
1,1002,2025-06-02,Ravi Kumar,Ball Pen,Stationery,5,10,Bengaluru
2,1003,2025-06-02,Neha Patel,Laptop,Electronics,1,55000,Delhi
3,1004,2025-06-03,Sunil Verma,Mouse,Electronics,2,500,Mumbai
4,1005,2025-06-04,Asha Rao,Pencil Box,Stationery,1,120,Chennai

In [17]:
# Challenge 1 - Total revenue by product?
df["Revenue"] = df["Quantity"] * df["Price"]
new_var = df[["Category","Revenue"]]
new_var.groupby(new_var["Category"]).sum()["Revenue"]

Category
Electronics    59200
Lifestyle        500
Stationery       570
Name: Revenue, dtype: int64

             Revenue
Category
Electronics    59200
Lifestyle        500
Stationery       570

In [23]:
#Optimized code
df["Revenue"] = df["Quantity"] * df["Price"]
x = df.groupby("Category")["Revenue"].sum()
print(x)

Category
Electronics    59200
Lifestyle        500
Stationery       570
Name: Revenue, dtype: int64

In [ ]:
#Test1